plugins {
    id 'java'
    id 'io.qameta.allure' version '3.0.0'
}

group = 'kz.kaspi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def allureVersion = '2.25.0'
def selenideVersion = '7.2.1'
def junitVersion = '5.10.2'
def slf4jVersion = '2.0.12'

allure {
    report {
        version.set(allureVersion)
    }

    adapter {
        aspectjWeaver.set(true)

        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}

dependencies {

    testImplementation "com.codeborne:selenide:${selenideVersion}"

    testImplementation "io.qameta.allure:allure-selenide:${allureVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"

    testImplementation "org.slf4j:slf4j-simple:${slf4jVersion}"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {

    useJUnitPlatform()

    /*
     * Передаём системные свойства в тесты.
     *
     * Например:
     *
     * ./gradlew test -DremoteUrl=https://selenoid.autotests.cloud/wd/hub
     *
     * Тогда в Java будет доступно:
     *
     * System.getProperty("remoteUrl")
     */
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events(
                    "started",
                    "skipped",
                    "failed",
                    "standard_error",
                    "standard_out"
            )

            exceptionFormat = "short"
        }
    }
}